// import the API.
// See xxx for the javadocs.
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.List;
import java.util.Random;

import bc.*;

public class Player {
	private static GameController gc;
	private static Team myTeam; //Red or Blue
	private static Team otherTeam;
	private static Planet myPlanet; //(Earth or Mars)
    private static PlanetMap map;	//Initial map 
    private static MapAnalyser mars;
    
    private static VecUnit units; //The list of all known units - updated each turn in the main loop
    private static VecUnit unitsInSpace; //The list of all units on the way to mars
    private static int totalKarbonite; //How much Karbonite is available on the starting map
    private static Random randomness = new Random(1042);    
    private static HashMap<Integer, Long> launchRound = new HashMap<Integer, Long>(); //List of scheduled launches (rocket id, round)
    
    public static void main(String[] args) {
        // Connect to the manager, starting the game
        gc = new GameController();
        myTeam = gc.team();
        if (myTeam == Team.Blue)
        	otherTeam = Team.Red;
        else
        	otherTeam = Team.Blue;

        //Cache the initial map
        myPlanet = gc.planet();
        map = gc.startingMap(myPlanet);  	
        
        if (myPlanet == Planet.Earth) {
	        //Start our research
	        gc.queueResearch(UnitType.Rocket); // Allows us to build rockets (100 turns)   
	        gc.queueResearch(UnitType.Worker); // Improves Karbonite harvesting (25 turns = 125)
	        gc.queueResearch(UnitType.Ranger); // Increase movement rate (25 turns = 150)
	        gc.queueResearch(UnitType.Mage); //Increase Damage (25 turns = 175)
	        gc.queueResearch(UnitType.Mage); //Increase Damage (75 turns = 250)
	        gc.queueResearch(UnitType.Mage); //Increase Damage (100 turns = 350)
	        gc.queueResearch(UnitType.Mage); //Blink (200 Turns = 550)
	        gc.queueResearch(UnitType.Ranger); // Increase Vision Range (100 Turns = 650)
	        gc.queueResearch(UnitType.Ranger); // Snipe (200 Turns = 950)
	        gc.queueResearch(UnitType.Healer); // Better Healing (25 Turns = 975)
	        gc.queueResearch(UnitType.Healer); // Better Healing (100 Turns = 1075)
	        gc.queueResearch(UnitType.Healer); // Overdrive (200 Turns = 1275)
        }
        
    	scanMap();
    	debug(1, "Total Karbonite on " + myPlanet + " is " + totalKarbonite);
        
        runPlanet();
    }
    private static final int debugLevel = 1;
    
    private static void debug(int level, String s) {
    	if (level <= debugLevel)
    		System.out.println(s);
    }
    
	/*
	 * All movement is based on gravity wells generated by points of interest
     * The gravity well maps are stored in arrays that map onto the Planet map
     * High scores are more interesting - units move to an adjacent tile with a higher score if possible
     * 
     * We create these maps each turn that a unit needs to move and only as needed
     */
    
    private static boolean nothingToMine = false; //Set to true once all the karbonite has been mined on Earth
    private static long[][] karboniteMap; //Initialised with starting values and updated as we sense tiles with new values
    private static boolean[][] passable; //Set to true if the location is passable (i.e. not water) - fixed
    
    private static double[][] workerMap = null;
    private static double[][] mageMap = null;
    private static double[][] rangerMap = null;
    private static double[][] healerMap = null;
    private static double[][] knightMap = null;
    
    private static long workerMapLastUpdated = -1;
    private static long mageMapLastUpdated = -1;
    private static long rangerMapLastUpdated = -1;
    private static long healerMapLastUpdated = -1;
    private static long knightMapLastUpdated = -1;
    
    /*
     * Returns the unit at the given location or null if there isn't one
     */
    private static Unit unitAt(MapLocation m) {
    	if (!gc.canSenseLocation(m) || !gc.hasUnitAtLocation(m))
    		return null;
    		
    	return gc.senseUnitAtLocation(m);
    }
    
    /*
     * Ripple out from the given edge (set of points) until a given number of our units have been found scoring each tile as we go - the nearer the higher the score
     * For each location we mark it as open (i.e. on the list to process), closed (processed) or unseen
     */
    public static void ripple(double[][] gravityMap, List<MapLocation> edge, double points, UnitType match, int max) {
    	int UNSEEN = 0, OPEN = 1, CLOSED = 2;
    	int[][] status = new int[(int)map.getWidth()][(int)map.getHeight()];
    	int distance = 0; //How far from the source are we
    	int matchCount = 0; //How many units of the right type have we seen
    	
    	for (MapLocation me: edge) {
    		status[me.getX()][me.getY()] = OPEN;
    	}
    	
    	debug(3, "ripple: starting points " + edge.size() + " value " + points + " stop when " + max + " " + match);
    	/*
    	 * This is a standard Breadth First Search
    	 * Since we want to know the distance from the source we maintain a current open list (edge)
    	 * and build up the next open list (nextEdge). When edge is processed (empty) we increment the distance and switch to the nextEdge
    	 */
    	while (!edge.isEmpty()) {
    		distance++;
    		List<MapLocation> nextEdge = new LinkedList<MapLocation>();
    		
        	for (MapLocation me: edge) {
        		if (status[me.getX()][me.getY()] != CLOSED) {
        			Unit unit = unitAt(me);
    				if (unit != null && unit.team() == myTeam &&
    						(match == null || match == unit.unitType())) {
						matchCount++;
						if (distance > 1 && matchCount >= max) { //We have reached the cutoff point
							debug(4, "Ripple match count met: complete at distance " + distance);
							return;
						}
					}
        			
	        		status[me.getX()][me.getY()] = CLOSED;
	        		debug(4, "Ripple SEEN " + me);

	    			//Score this tile
					gravityMap[me.getX()][me.getY()] += points/(distance*distance);
		       		
	    			//We add adjacent tiles to the next search if they are traversable
					for (MapLocation t:allMoveNeighbours(me)) {
		    			if (status[t.getX()][t.getY()] == UNSEEN) {
			    			nextEdge.add(t);
			    			status[t.getX()][t.getY()] = OPEN;
			    			debug(4, "ripple Added " + t);
		    			}
		    		}
    			}
    		}
    		debug(4, "Ripple distance " + distance + " edge size = " + nextEdge.size());
    		
    		edge = nextEdge;
    	}
    	
    	debug(3, "Ripple queue empty: complete at distance " + distance);
    }
    
    public static void ripple(double[][] gravityMap, MapLocation t, double points, UnitType match, int max) {
    	List<MapLocation> edge = new LinkedList<MapLocation>();
    	edge.add(t);

    	ripple(gravityMap, edge, points, match, max);
    }
    
    public static void ripple(double[][] gravityMap, int x, int y, double points, UnitType match, int max) {
    	List<MapLocation> edge = new LinkedList<MapLocation>();
    	edge.add(new MapLocation(myPlanet, x, y));

    	ripple(gravityMap, edge, points, match, max);
    }
    
    private static int maxUnitsOnRocket(UnitType t) {
    	switch (t) {
    	case Mage:
    		return 4;
    	case Ranger:
    		return 2;
    	default:
    		return 1;
    	}
    }
    /*
     * addRockets
     * 
     * Adds in gravity for each active rocket on earth looking for passengers
     * Currently we limit a rocket to
     *  1 Worker
     *  2 Rangers
     *  4 Mages
     *  1 Healer
     */
    private static void addRockets(double[][] map, UnitType match) {
    	//Add Rockets that are ready to board and have space
		if (myPlanet == Planet.Earth) {
    		for (Unit r: rockets) {
    			VecUnitID loaded = r.structureGarrison();
    			int count = 0;
    			for (long i=0; i<loaded.size(); i++) {
    				Unit u = gc.unit(loaded.get(i));
    				if (u.unitType() == match)
    					count++;
    			}
    			
    			int allowed = maxUnitsOnRocket(match) - count;
    			if (allowed > 0)
    				ripple(map, r.location().mapLocation(), 1000, match, allowed);
    		}
		}
    }
    
    /*
     * Returns true if a unit can attack and damage us
     */
    private static boolean isCombatUnit(Unit u) {
    	switch (u.unitType()) {
    	case Knight:
    	case Ranger:
    	case Mage:
    		return true;
    	default:
    		return false;
    	}
    }
    
    /*
     * addDangerZones
     * 
     * subtracts from all tiles on the map within the attack range of enemy units we can see
     */
    private static void addDangerZones(double[][] map) {
    	//Add enemies danger zones
    	for (Unit u:enemies) {
    		if (isCombatUnit(u)) { //This unit can attack and damage us
	    		MapLocation enemyLoc = u.location().mapLocation();
	    		VecMapLocation tiles =  gc.allLocationsWithin(enemyLoc, u.attackRange());
	    		for (int i=0; i<tiles.size(); i++) {
	    			MapLocation m = tiles.get(i);
	    			int x = m.getX(), y = m.getY();
	    			map[x][y] -= 100;
	    		}
    		}
    	}	
    }
    
    private static void createWhiteNoiseMap(double[][] noise) {
    	for (int x=0; x<map.getWidth(); x++) {
    		for (int y=0; y<map.getHeight(); y++) {
    			noise[x][y] = randomness.nextDouble() / 1000.0;
    		}
    	}
    }
    
    /*
     * Rangers are combat units
     * They move towards enemy units, our workers (to protect them) and rockets.
     * 
	 * - Enemy unit - Strength = 5*Cost, Max = 5
	 * - Worker ally - Strength = Cost, Max = 1
	 * - Rocket - Strength = 1000, Max = 1
     */
    private static void updateRangerMap() {
    	if (rangerMapLastUpdated == gc.round()) //We have already done it
    		return;
    	
    	rangerMapLastUpdated = gc.round();
    	createWhiteNoiseMap(rangerMap);
    	List<MapLocation> targets = new ArrayList<MapLocation>();
    	int rangerCount = myLandUnits[UnitType.Ranger.ordinal()];
    	
    	//Add enemies
    	for (Unit u:enemies) {
    		//We want to be at our attack distance from each enemy
    		MapLocation enemyLoc = u.location().mapLocation();
    		VecMapLocation tiles =  gc.allLocationsWithin(enemyLoc, 50);
    		for (int i=0; i<tiles.size(); i++) {
    			MapLocation m = tiles.get(i);
    			//We only want the tiles that are a reasonable distance from the enemy
    			if (m.distanceSquaredTo(enemyLoc) > 30)
    				targets.add(m);
    			else {
    				int x = m.getX(), y = m.getY();
    				rangerMap[x][y] -= 100;
    			}
    		}
    	}
    	debug(4, "updateRangerMap: added " + enemies.size() + " enemies and " + targets.size() + " tiles");
    	ripple(rangerMap, targets, 100, UnitType.Ranger, rangerCount);
    	
    	addRockets(rangerMap, UnitType.Ranger);
    }
    
    private static void updateMageMap() {
    	if (mageMapLastUpdated == gc.round()) //We have already done it
    		return;
    	
    	mageMapLastUpdated = gc.round();
    	createWhiteNoiseMap(mageMap);
    	List<MapLocation> targets = new ArrayList<MapLocation>();
    	int mageCount = myLandUnits[UnitType.Mage.ordinal()];
    	
    	//Add enemies
    	for (Unit u:enemies) {
    		//We want to be at our attack distance from each enemy
    		MapLocation enemyLoc = u.location().mapLocation();
    		VecMapLocation tiles =  gc.allLocationsWithin(enemyLoc, 30);
    		for (int i=0; i<tiles.size(); i++) {
    			MapLocation m = tiles.get(i);
    			//We only want the tiles that are a reasonable distance from the enemy
    			if (m.distanceSquaredTo(enemyLoc) > 20)
    				targets.add(m);
    			else {
    				int x = m.getX(), y = m.getY();
    				mageMap[x][y] -= 100;
    			}
    		}
    	}
    	
    	ripple(mageMap, targets, 100, UnitType.Mage, mageCount);
    	
    	addRockets(mageMap, UnitType.Mage);
    }
    
    /*
     * Healers need to move towards damaged allies (not structures)
     * Like all other units they will board waiting rockets
     */
    private static void updateHealerMap() {
    	if (healerMapLastUpdated == gc.round()) //We have already done it
    		return;
    	
    	healerMapLastUpdated = gc.round();
    	createWhiteNoiseMap(healerMap);
    	List<MapLocation> targets = new ArrayList<MapLocation>();
    	int healerCount = myLandUnits[UnitType.Healer.ordinal()];
    	
    	//Add damaged units
    	for (Unit u:unitsToHeal)
    		targets.add(u.location().mapLocation());
    	ripple(healerMap, targets, 100, UnitType.Healer, healerCount);
    	
    	addDangerZones(healerMap);
		addRockets(healerMap, UnitType.Healer);
    }
    
    private static void updateKnightMap() {
    	if (knightMapLastUpdated == gc.round()) //We have already done it
    		return;
    	
    	knightMapLastUpdated = gc.round();
    	createWhiteNoiseMap(knightMap);
    	List<MapLocation> targets = new ArrayList<MapLocation>();
    	int knightCount = myLandUnits[UnitType.Knight.ordinal()];
    	
    	//Add enemies
    	for (Unit u:enemies)
    		targets.add(u.location().mapLocation());
    	
    	ripple(knightMap, targets, 100, UnitType.Knight, knightCount);
    	
    	addRockets(knightMap, UnitType.Knight);
    }
    
    /*
     * Workers are the busiest!
     * They respond to Karbonite, blueprints and damaged structures
     * Like all units they also board rockets when built
     */
    private static void updateWorkerMap() {
    	if (workerMapLastUpdated == gc.round()) //We have already done it
    		return;
    	
    	workerMapLastUpdated = gc.round();
    	createWhiteNoiseMap(workerMap);
		List<MapLocation> targets = new ArrayList<MapLocation>();
		int workerCount = myLandUnits[UnitType.Worker.ordinal()];
		
		//Add Karbonite deposits
		if (!nothingToMine) {
			for (int x=0; x<map.getWidth(); x++) {
				for (int y=0; y<map.getHeight(); y++) {
					if (karboniteMap[x][y] > 0) {
						targets.add(new MapLocation(myPlanet, x, y));
					}
				}
			}
			ripple(workerMap, targets, 10, UnitType.Worker, workerCount);
			if (myPlanet == Planet.Earth && targets.size() == 0)
				nothingToMine = true;
		}
		
		//Add blueprints and damaged buildings
		targets.clear();
		for (Unit b: unitsToBuild) {
			MapLocation m = b.location().mapLocation();
			int x = m.getX(), y = m.getY();
			targets.add(b.location().mapLocation());
			workerMap[x][y] -= 200;
		}
		for (Unit b: unitsToRepair) {
			MapLocation m = b.location().mapLocation();
			int x = m.getX(), y = m.getY();
			targets.add(b.location().mapLocation());
			workerMap[x][y] -= 200;
		}
		ripple(workerMap, targets, 200, UnitType.Worker, Math.min(workerCount, 8));
		
		addDangerZones(workerMap);
		addRockets(workerMap, UnitType.Worker);
    }
    
    private static double[][] getGravityMap(UnitType type) {
    	switch (type) {
    	case Worker:
    		updateWorkerMap();
    		return workerMap;
    	case Ranger:
    		updateRangerMap();
    		return rangerMap;
    	case Mage:
    		updateMageMap();
    		return mageMap;
    	case Healer:
    		updateHealerMap();
    		return healerMap;
    	case Knight:
    		updateKnightMap();
    		return knightMap;
    	default:
    		return null;
    	}
    }
    
    /*
     * Scan the map data and record the locations of karbonite, the number of passable neighbours each tile has
     * and return the total karbonite on the map
     * 
     * This is called once on the first turn
     */
    private static void scanMap() {
    	int w = (int) map.getWidth(), h = (int) map.getHeight();
    	totalKarbonite = 0;
    	karboniteMap = new long[w][h];
    	passable = new boolean[w][h];
    	rangerMap = new double[w][h];
    	mageMap = new double[w][h];
    	healerMap = new double[w][h];
    	knightMap = new double[w][h];
    	workerMap = new double[w][h];
    	
    	for (int x = 0; x<map.getWidth(); x++) {
    		for (int y=0; y<map.getHeight(); y++) {
    			MapLocation here = new MapLocation(myPlanet, x, y);
    			karboniteMap[x][y] = map.initialKarboniteAt(here);
    			totalKarbonite += karboniteMap[x][y];    			
    			passable[x][y] = (map.onMap(here) && map.isPassableTerrainAt(here) > 0);
    		}
    	}
    	
    	if (myPlanet == Planet.Earth) {
    		if (totalKarbonite == 0)
    			nothingToMine = true;
    	}
    	
    	mars = new MapAnalyser(gc);
    }   
    
    /*
     * Given a gravity map we find the highest scoring tile adjacent to us
     * This could be one of our static buildings or an empty tile
     */
    private static Direction bestMove(Unit t, double[][] gravityMap) {
    	Direction best = null;
    	
    	if (!t.location().isOnMap())
    		return null;
    	
    	MapLocation myLoc = t.location().mapLocation();
    	double bestScore = gravityMap[myLoc.getX()][myLoc.getY()];
    	debug(4, "bestMove from " + myLoc + " current score " + bestScore);
    	List<MapLocation> options = allMoveNeighbours(myLoc);
    	for (MapLocation test: options) {
    		Direction d = myLoc.directionTo(test);
    		if (gravityMap[test.getX()][test.getY()] > bestScore) {
    			bestScore = gravityMap[test.getX()][test.getY()];
    			best = d;
    		}
    	}
    	debug (4, "is " + best + " with a score of " + bestScore);
		return best;
    }
    
    /*
     * updateKarbonite
     * 
     * Use current sense data to update any changes to karbonite
     * If Earth now has no Karbonite we can skip the update as no more will appear
     */
    private static void updateKarbonite() {
    	
    	if (!nothingToMine) {
	    	for (int x = 0; x<map.getWidth(); x++) {
	    		for (int y=0; y<map.getHeight(); y++) {
	    			MapLocation test = new MapLocation(myPlanet, x, y);
	    			if (gc.canSenseLocation(test)) {
	    				karboniteMap[x][y] = gc.karboniteAt(test);
	    			}
	    		}
	    	}
    	}	    	
    	
    	if (myPlanet == Planet.Mars) {
    		if (gc.asteroidPattern().hasAsteroid(gc.round())) {
    			MapLocation strike = gc.asteroidPattern().asteroid(gc.round()).getLocation();
    			long karbonite = gc.asteroidPattern().asteroid(gc.round()).getKarbonite();
    			int x = strike.getX(), y = strike.getY();
    			karboniteMap[x][y] += karbonite;
    		}
    	}
    }
    
    private static int[] myLandUnits = new int[UnitType.values().length]; //Counts of how many units we have indexed by unit type (ordinal)
    private static int[] mySpaceUnits = new int[UnitType.values().length]; //Counts of how many units we have indexed by unit type (ordinal)
    private static List<Unit> unitsToBuild = new ArrayList<Unit>(); //List of current blueprints that need building
    private static List<Unit> unitsToHeal = new ArrayList<Unit>(); //List of units that need healing
    private static List<Unit> unitsToRepair = new ArrayList<Unit>(); //List of buildings that need repair
    private static List<Unit> rockets = new ArrayList<Unit>(); //List of rockets (to Load into if on Earth, or unload from on Mars)
    private static List<Unit> enemies = new ArrayList<Unit>(); //List of all enemy units in sight
    private static List<Unit> factories = new ArrayList<Unit>(); //List of all our factories
    
    /*
     * Loop through the units we are aware of and update our cache
     * Called once each turn
     */
    private static void updateUnits() {
        units = gc.units(); //All the units we can see on the map (but not the ones in garisons)
        unitsInSpace = gc.unitsInSpace(); //All the units in space
    	Arrays.fill(myLandUnits, 0);
    	Arrays.fill(mySpaceUnits, 0);
    	unitsToBuild.clear();
    	unitsToHeal.clear();
    	unitsToRepair.clear();
    	rockets.clear();
    	enemies.clear();
    	factories.clear();
    	
    	for (int i = 0; i < units.size(); i++) {
            Unit unit = units.get(i);
            
            if (unit.location().isOnMap()) {
            	if (unit.team() == myTeam) {
            		myLandUnits[unit.unitType().ordinal()]++;
            		if (unit.unitType().equals(UnitType.Factory) || unit.unitType().equals(UnitType.Rocket)) {
            			if (unit.structureIsBuilt() == 0)
            				unitsToBuild.add(unit);
            			else if (unit.health() < unit.maxHealth())
            				unitsToRepair.add(unit);
            			
            			if (unit.unitType().equals(UnitType.Factory))
            				factories.add(unit);
            			else if (unit.unitType().equals(UnitType.Rocket) && unit.rocketIsUsed() == 0)
            				rockets.add(unit);
            			
            			VecUnitID garrison = unit.structureGarrison();
            			for (int j=0; j<garrison.size(); j++) {
            				int id = garrison.get(j);
            				myLandUnits[gc.unit(id).unitType().ordinal()]++;
            			}
            		} else {
            			if (unit.health() < unit.maxHealth())
            				unitsToHeal.add(unit);
            		}
            	} else { //enemies
            		enemies.add(unit);
            	}
            }
    	}
    	
    	for (int i=0; i<unitsInSpace.size(); i++) {
    		Unit unit = unitsInSpace.get(i);
    		mySpaceUnits[unit.unitType().ordinal()]++;
    	}
    	
    	String unitInfo = "";
    	for (UnitType t: UnitType.values())
    		if (myLandUnits[t.ordinal()] > 0)
    			unitInfo += t + " = " + myLandUnits[t.ordinal()] + " ";
    	if (unitInfo.length() > 0)
    		debug(1, "Round " + gc.round() + ": On " + myPlanet + ": " + unitInfo);
    	
    	unitInfo = "";
    	for (UnitType t: UnitType.values())
    		if (mySpaceUnits[t.ordinal()] > 0)
    			unitInfo += t + " = " + mySpaceUnits[t.ordinal()] + " ";
    	if (unitInfo.length() > 0)
    		debug(1, "Round " + gc.round() + ": In space: " + unitInfo);
    	
    	for (int rnd=0; rnd<200; rnd++) {
    		VecRocketLanding landings = gc.rocketLandings().landingsOn(gc.round()+rnd);
    		for (int l=0; l<landings.size(); l++)
    			debug(1, "Rocket Landing on @ " + landings.get(l).getDestination() + " in "+ rnd + " rounds");
    	}
    }
   
    /*
     * Returns an array containing all the open neighbours of a map location
     * Open means on the map and not water and doesn't contain a unit
     */
    private static List<MapLocation> allOpenNeighbours(MapLocation l) {
    	List<MapLocation> result = new ArrayList<MapLocation>();
    	VecMapLocation all = gc.allLocationsWithin(l, 2);
    	
    	for (int i=0; i<all.size(); i++) {
    		MapLocation test = all.get(i);
    		if (passable[test.getX()][test.getY()] && !gc.hasUnitAtLocation(test))
				result.add(test);
		}
    	
    	return result;
    }
    
    /*
     * Returns true if the unit is our and a working factory
     */
    private static boolean isOurFactory(Unit u) {
    	if (u == null || u.team() != myTeam)
    		return false;
    	
    	return (u.unitType() == UnitType.Factory && u.structureIsBuilt() > 0);
    }
    
    /*
     * Returns an array containing all the neighbours of a map location we can move to
     * Open means on the map and not water and doesn't contain a blocking structure
     */
    private static List<MapLocation> allMoveNeighbours(MapLocation l) {
    	List<MapLocation> result = new ArrayList<MapLocation>();
    	VecMapLocation all = gc.allLocationsWithin(l, 2);
    	
    	for (int i=0; i<all.size(); i++) {
    		MapLocation test = all.get(i);
    		int x = test.getX(), y = test.getY();
    		Unit u = unitAt(test);
			if (passable[x][y] &&
					(u == null || isOurFactory(u)))
				result.add(test);
		}
    	
    	return result;
    }
    
    private static void manageWorker(Unit unit) {
    	if (!unit.unitType().equals(UnitType.Worker))
    		return;
    	
    	int id = unit.id();
    	
    	if (!unit.location().isInSpace() && unit.location().isOnMap()) {			
			//Do we want to move to a better location
            if (gc.isMoveReady(id))
            	moveUnit(unit);
            
    		MapLocation loc = unit.location().mapLocation();
        	List<MapLocation> options = allOpenNeighbours(loc);
        	Direction dir = null;
        	if (!options.isEmpty())
        		dir = loc.directionTo(options.get(0));

        	//Check to see if we can replicate
        	if (dir != null && myLandUnits[UnitType.Worker.ordinal()] + mySpaceUnits[UnitType.Worker.ordinal()] < 16) {
            	if (gc.canReplicate(id, dir)) {
            		gc.replicate(id, dir);
            		myLandUnits[UnitType.Worker.ordinal()]++;
            		debug(2, "worker replicating");
            	}
        	}	                    
            
            //Can we help build something
            if (unit.workerHasActed() == 0) {            
	            VecUnit nearby = gc.senseNearbyUnits(loc, 2); //Adjacent units
						
				for (int k = 0; k < nearby.size(); k++) {
					Unit other = nearby.get(k);
					if (gc.canBuild(id, other.id())) {
						gc.build(id, other.id());
						debug(2, "worker building");
						break;
					}
				}
            }

			//Can we Harvest
			if (unit.workerHasActed() == 0) {
				for (Direction d: Direction.values()) {
					if (gc.canHarvest(id, d)) {
						gc.harvest(id, d);
						debug(2, "worker harvesting");
						break;
					}
				}
			}
			
			/*
			 * Now check to see if we want to build a factory or a rocket
			 */			
			if (dir != null && unit.workerHasActed() == 0 && gc.planet() == Planet.Earth) {
				int factoriesNeeded = 3 - myLandUnits[UnitType.Factory.ordinal()];
				int unitsToTransport = (myLandUnits[UnitType.Worker.ordinal()] + 
						myLandUnits[UnitType.Ranger.ordinal()] +
						myLandUnits[UnitType.Mage.ordinal()] +
						myLandUnits[UnitType.Knight.ordinal()] +
						myLandUnits[UnitType.Healer.ordinal()]);
				int rocketsNeeded = (unitsToTransport+7) / 8;
				if (factoriesNeeded > 0 && factoriesNeeded >= rocketsNeeded &&
						gc.karbonite() >= bc.bcUnitTypeBlueprintCost(UnitType.Factory) &&
						gc.canBlueprint(id, UnitType.Factory, dir)) {
					gc.blueprint(id, UnitType.Factory, dir);
					debug(2, "worker blueprinting factory");
					myLandUnits[UnitType.Factory.ordinal()]++;
				} else if (rocketsNeeded > 0 && rocketsNeeded >= factoriesNeeded &&
						gc.karbonite() >= bc.bcUnitTypeBlueprintCost(UnitType.Rocket) &&
						gc.canBlueprint(id, UnitType.Rocket, dir)) {
					gc.blueprint(id, UnitType.Rocket, dir);
					debug(2, "worker blueprinting rocket");
					myLandUnits[UnitType.Rocket.ordinal()]++;
				}
			}
        }
    }
    
    private static int marsZone = 0; //This is the zone we want to land in next
    
    /*
     * Pick the next valid zone on mars
     * It has to have viable landing sites
     */
    private static void nextZone() {
	  //Send next rocket to next zone
		boolean found = false;
		int startZone = marsZone;
		while (!found) {
	    	marsZone++;
	    	if (marsZone >= mars.zones.size())
	    		marsZone = 0;
	    	found = (marsZone == startZone || mars.zones.get(marsZone).landingSites.size() > 0);
		}
	}
		
    private static MapLocation launchDestination() {
    	if (marsZone < 0) //Mars is full!
    		return null;
    	
    	//Pick a random tile in the given zone
    	MapZone zone = mars.zones.get(marsZone);
    	int size = zone.landingSites.size();
    	if (size == 0)
    		return null;
    	
    	return zone.landingSites.get(randomness.nextInt(size));  	
    }
    
    private static long getLaunchRound(Unit u) {
    	if (u.structureIsBuilt() == 0)
    		return 749; //TODO - find constant and use it
    	
    	int id = u.id();
    	if (launchRound.containsKey(id))
    		return launchRound.get(id);
    	
    	long round = 749;
    	if (gc.round() + 50 < round)
    		round = gc.round() + 50;
    	
    	launchRound.put(id, round);
    	debug(3, "Rocket id " + id + " will launch on round " + round);
    	return round;
    }
    
    /*
     * Rockets leave Earth when full or we reach the launch time
     */
    private static void manageRocket(Unit unit) {
    	if (!unit.unitType().equals(UnitType.Rocket))
    		return;
    	
    	int id = unit.id();
    	if (myPlanet == Planet.Earth) {
    		//Check to see if we are have a launch time or are full
    		MapLocation dest = launchDestination();
    		if (dest != null && gc.canLaunchRocket(id, dest)) {
    			boolean launchNow = (unit.structureGarrison().size() >= unit.structureMaxCapacity());
    			if (!launchNow && gc.round() >= getLaunchRound(unit))
    				launchNow = true;
    			if (launchNow) {
    				debug(1, "Launching rocket " + id + " to " + dest + " ETA " + gc.currentDurationOfFlight() + " rnds");
    				gc.launchRocket(id, dest);
    				launchRound.remove(id);
    				if (!mars.zones.get(marsZone).landingSites.remove(dest)) {
    					debug(0, "Failed to remove " + dest + " from zone " + marsZone);
    				}
    				nextZone();
    			}
    		}
    	} else {
			//We don't know the unit type so use the worker movement map
    		while (unit.structureGarrison().size() > 0) {
				Direction dir = bestMove(unit, getGravityMap(UnitType.Worker));
		    	if (dir == null || !gc.canUnload(id, dir))
		    		break;
		    	gc.unload(id, dir);
		    	debug(2, "unloading from rocket");
    		}
    	}
    }
    
    /*
     * Factories produce combat units and allow other units (workers) to move through them
     */
    private static void manageFactory(Unit unit) {
    	if (!unit.unitType().equals(UnitType.Factory))
    		return;
    	
    	int fid = unit.id();
    	
    	//Unload units if possible
    	while (unit.structureGarrison().size() > 0) {
	    	Direction dir = bestMove(unit, getGravityMap(UnitType.Worker));
	    	if (dir == null || !gc.canUnload(fid, dir))
	    		break;
    		gc.unload(fid, dir);
    		debug(2, "unloading from factory");
    	}
    	
    	//Produce units
    	//We want squads consisting of 1 ranger, 3 mages and a healer
    	UnitType produce = UnitType.Ranger;
    	if (myLandUnits[UnitType.Mage.ordinal()] < 3 * myLandUnits[UnitType.Ranger.ordinal()])
    		produce = UnitType.Mage;
    	else if (myLandUnits[UnitType.Healer.ordinal()] < myLandUnits[UnitType.Ranger.ordinal()])
    		produce = UnitType.Healer;
    	
    	if (gc.canProduceRobot(fid, produce)) {
			gc.produceRobot(fid, produce);
		}
    }
    
    private static void manageMage(Unit unit) {
    	int id = unit.id();
    	boolean canAttack = (unit.attackHeat() < 10);
    	
    	if (canAttack) {
    		int targetId = bestTarget(unit);
    		if (targetId > -1) {
    			gc.attack(id, targetId);
    			debug(2, "Unit " + id + " " + unit.unitType() + " firing on " + targetId);
    			canAttack = false;
    		}
    	}  	
    	
    	//Do we want to move to a better location
    	if (unit.isAbilityUnlocked() > 0 && unit.abilityHeat() < 10) {
    		MapLocation here = unit.location().mapLocation();
    		//We can blink to best location in sight range
    		updateMageMap();
    		double bestScore = mageMap[here.getX()][here.getY()];
    		MapLocation bestOption = here;
    		VecMapLocation options = gc.allLocationsWithin(here, unit.abilityRange());
    		for (int i=0; i<options.size(); i++) {
    			MapLocation o = options.get(i);
    			if (mageMap[o.getX()][o.getY()] > bestScore) {
    				bestScore = mageMap[o.getX()][o.getY()];
    				bestOption = o;
    			}
    		}
    		if (here.distanceSquaredTo(bestOption) >= 2)
    			gc.blink(id, bestOption);
    	}
    	if (gc.isMoveReady(id))
        	moveUnit(unit);
        	
        if (canAttack) {
    		int targetId = bestTarget(unit);
    		if (targetId > -1) {
    			gc.attack(id, targetId);
    			debug(2, "Unit " + id + " " + unit.unitType() + " firing on " + targetId);
    		}
    	}  
    }
    
    /*
     * manageRanger
     * 
     * As a combat unit we attack enemies and scout
     */
    private static void manageRanger(Unit unit) {
    	int id = unit.id();
    	boolean canAttack = (unit.attackHeat() < 10);
    	
    	//Rangers need to be mobile - we need to be able to shoot then move or to move then shoot
    	
    	if (canAttack) {
    		int targetId = bestTarget(unit);
    		if (targetId > -1) {
    			gc.attack(id, targetId);
    			debug(2, "Unit " + id + " " + unit.unitType() + " firing on " + targetId);
        		canAttack = false;
    		}
    	}  	
    	
    	//Do we want to move to a better location
        if (gc.isMoveReady(id))
        	moveUnit(unit);
        	
        if (canAttack) {
    		int targetId = bestTarget(unit);
    		if (targetId > -1) {
    			gc.attack(id, targetId);
    			debug(2, "Unit " + id + " " + unit.unitType() + " firing on " + targetId);
    		}
    	}  
    }
    
    private static void manageKnight(Unit unit) {
    	manageRanger(unit);
    }
    
    /*
     * manageHealer
     * 
     * We don't fight so we heal anyone in range
     */
    private static void manageHealer(Unit unit) {
    	int id = unit.id();
    	
    	if (gc.isMoveReady(id))
        	moveUnit(unit);
    	
    	if (unit.location().isOnMap()) {
	    	VecUnit inSight = gc.senseNearbyUnitsByTeam(unit.location().mapLocation(), unit.attackRange(), myTeam);
	    	for (int i=0; i<inSight.size(); i++) {
	    		Unit ally = inSight.get(i);
	    		if (unit.attackHeat() < 10 && ally.health() < ally.maxHealth() && gc.canHeal(id, ally.id())) {
	    			gc.heal(id, ally.id());
	    			debug(2, "Healing " + ally.unitType() + " @ " + ally.location().mapLocation());
	    			break;
	    		}
	    	}
    	}
    }
    
    /*
     * Look for a target in range and pick the one with the most damage to fire on
     */
    private static int bestTarget(Unit unit) {
    	if (!unit.location().isOnMap())
    		return -1;
    	
    	VecUnit inSight = gc.senseNearbyUnitsByTeam(unit.location().mapLocation(), unit.attackRange(), otherTeam);
    	//Pick the enemy with the most damage that is in range
    	int best = -1, id = unit.id();
    	long mostDamage = -1;
    	
    	for (int i=0; i<inSight.size(); i++) {
    		Unit enemy = inSight.get(i);
    		if (gc.canAttack(id, enemy.id()) && enemy.maxHealth() - enemy.health() > mostDamage) {
    			best = enemy.id();
    			mostDamage = enemy.maxHealth() - enemy.health();
    		}
    	}
    	
    	return best;
    }
    
    
    private static void moveUnit(Unit unit) {
    	if (!unit.location().isOnMap())
    		return;
    	
    	Direction d = bestMove(unit, getGravityMap(unit.unitType()));
    	
    	if (d != null) {
        	MapLocation loc = unit.location().mapLocation();
        	int id = unit.id();
    		MapLocation dest = loc.add(d);
    		
    		if (gc.canMove(id, d)) {
    			gc.moveRobot(id, d);
    		} else if (unit.location().isInGarrison()) {
    			Unit structure = unitAt(loc);
    			if (structure != null && gc.canUnload(structure.id(), d)) {
    				gc.unload(structure.id(), d);
    			}
    		} else { //Check to see if there is a structure of ours there
    			Unit structure = unitAt(dest);
    			if (structure != null) {
	    			if (gc.canLoad(structure.id(), id)) {
	    				gc.load(structure.id(), id);
	    			}
    			}
    		}
    	}	
    }
    
    private static void runPlanet() {
    	
        while (true) {
        	try {
        		long startTime = System.currentTimeMillis();

	            updateUnits(); //All units we can see - allies and enemies
	            updateKarbonite(); //Current known karbonite values
	            
	            for (int i = 0; i < units.size(); i++) {
	                Unit unit = units.get(i);
	                
	                if (unit.team() == myTeam) {
		                // Most methods on gc take unit IDs, instead of the unit objects themselves.
		  
	                	switch(unit.unitType()) {
	                	case Worker:
	                		manageWorker(unit);
	                		break;
	                	case Knight:
	                		manageKnight(unit);
	                		break;
	                	case Ranger:
	                		manageRanger(unit);
	                		break;
	                	case Mage:
	                		manageMage(unit);
	                		break;
	                	case Rocket:
	                		manageRocket(unit);
	                		break;
	                	case Factory:
	                		manageFactory(unit);
	                		break;
	                	case Healer:
	                		manageHealer(unit);
	                	default: //Unknown unit
	                		break;
	                	}
		                
	                }
	            }
	            // Submit the actions we've done, and wait for our next turn.

        		long endTime = System.currentTimeMillis();
        		debug(1, "Time spent on round " + gc.round() + " = " + (endTime - startTime));
	            gc.nextTurn();
        	} catch (Exception e) {
        		//Ignore
        		debug(0, "Caught exception " + e);
        		e.printStackTrace();
        	}
        }
    }
}